ALTER TABLE leads ADD COLUMN archived_at DATETIME NULL AFTER unsubscribed;
ALTER TABLE leads ADD COLUMN deleted_at DATETIME NULL AFTER archived_at;
ALTER TABLE leads ADD INDEX leads_archived_at_index (archived_at);
ALTER TABLE leads ADD INDEX leads_deleted_at_index (deleted_at);
ALTER TABLE leads ADD INDEX leads_business_archived_index (business_profile_id, archived_at, deleted_at);

ALTER TABLE email_templates ADD COLUMN preheader VARCHAR(255) NULL AFTER subject;
ALTER TABLE email_templates ADD COLUMN body_html MEDIUMTEXT NULL AFTER body;
ALTER TABLE email_templates ADD COLUMN body_text MEDIUMTEXT NULL AFTER body_html;

UPDATE email_templates
SET body_text = body
WHERE (body_text IS NULL OR body_text = '') AND body IS NOT NULL;

ALTER TABLE email_queue ADD COLUMN rendered_subject VARCHAR(255) NULL AFTER template_id;
ALTER TABLE email_queue ADD COLUMN rendered_preheader VARCHAR(255) NULL AFTER rendered_subject;
ALTER TABLE email_queue ADD COLUMN rendered_html MEDIUMTEXT NULL AFTER rendered_preheader;
ALTER TABLE email_queue ADD COLUMN rendered_text MEDIUMTEXT NULL AFTER rendered_html;
ALTER TABLE email_queue ADD COLUMN rendered_variables LONGTEXT NULL AFTER rendered_text;

CREATE TABLE IF NOT EXISTS campaign_skips (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    business_profile_id INT UNSIGNED NOT NULL,
    campaign_id INT UNSIGNED NOT NULL,
    lead_id INT UNSIGNED NULL,
    lead_company_name VARCHAR(190) NULL,
    lead_contact_name VARCHAR(190) NULL,
    lead_email VARCHAR(190) NULL,
    reason VARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY campaign_skips_campaign_index (campaign_id),
    KEY campaign_skips_business_reason_index (business_profile_id, reason),
    CONSTRAINT campaign_skips_business_fk FOREIGN KEY (business_profile_id) REFERENCES business_profiles (id) ON DELETE CASCADE,
    CONSTRAINT campaign_skips_campaign_fk FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE,
    CONSTRAINT campaign_skips_lead_fk FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO email_templates (business_profile_id, name, category, subject, preheader, body, body_html, body_text, followup_stage, active, created_at, updated_at) VALUES
(1, 'Initial Outreach - Skincare/Cosmetic Formulators', 'Skincare / cosmetic formulators', 'Peptide sourcing support for {{company_name}}', 'MOQ flexibility, documentation support, and batch transparency for skincare formulation buyers.', 'Hello {{contact_name}},\n\nI am reaching out from {{brand_name}}. Atlas BioLabs supports peptide sourcing with MOQ flexibility, documentation support, batch transparency, and supply coordination for qualified B2B buyers.\n\nFor skincare and cosmetic formulation teams, we focus on practical sourcing conversations, documentation readiness, and commercially clear follow-up.\n\nIf {{company_name}} is reviewing supply options, we would be glad to share next steps.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', '<p style="margin:0 0 16px;">Hello {{contact_name}},</p><p style="margin:0 0 16px;">I am reaching out from {{brand_name}}. Atlas BioLabs supports peptide sourcing with MOQ flexibility, documentation support, batch transparency, and supply coordination for qualified B2B buyers.</p><p style="margin:0 0 16px;">For skincare and cosmetic formulation teams, we focus on practical sourcing conversations, documentation readiness, and commercially clear follow-up.</p><p style="margin:0;">If {{company_name}} is reviewing supply options, we would be glad to share next steps.</p>', 'Hello {{contact_name}},\n\nI am reaching out from {{brand_name}}. Atlas BioLabs supports peptide sourcing with MOQ flexibility, documentation support, batch transparency, and supply coordination for qualified B2B buyers.\n\nFor skincare and cosmetic formulation teams, we focus on practical sourcing conversations, documentation readiness, and commercially clear follow-up.\n\nIf {{company_name}} is reviewing supply options, we would be glad to share next steps.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', 0, 1, NOW(), NOW()),
(1, 'Initial Outreach - Ingredient Distributors', 'Ingredient distributors', 'Documented peptide sourcing coordination for {{company_name}}', 'A professional supplier introduction for distribution-focused teams.', 'Hello {{contact_name}},\n\n{{brand_name}} supports peptide sourcing with MOQ flexibility, documentation support, batch transparency, and supply coordination for qualified B2B buyers.\n\nFor ingredient distribution teams, we focus on clear commercial communication, documentation alignment, and sourcing continuity.\n\nIf {{company_name}} is evaluating peptide supply partners, we can share sourcing details and RFQ next steps.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', '<p style="margin:0 0 16px;">Hello {{contact_name}},</p><p style="margin:0 0 16px;">{{brand_name}} supports peptide sourcing with MOQ flexibility, documentation support, batch transparency, and supply coordination for qualified B2B buyers.</p><p style="margin:0 0 16px;">For ingredient distribution teams, we focus on clear commercial communication, documentation alignment, and sourcing continuity.</p><p style="margin:0;">If {{company_name}} is evaluating peptide supply partners, we can share sourcing details and RFQ next steps.</p>', 'Hello {{contact_name}},\n\n{{brand_name}} supports peptide sourcing with MOQ flexibility, documentation support, batch transparency, and supply coordination for qualified B2B buyers.\n\nFor ingredient distribution teams, we focus on clear commercial communication, documentation alignment, and sourcing continuity.\n\nIf {{company_name}} is evaluating peptide supply partners, we can share sourcing details and RFQ next steps.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', 0, 1, NOW(), NOW()),
(1, 'Initial Outreach - Contract Manufacturers', 'Contract manufacturers', 'Supply coordination support for {{company_name}}', 'Atlas BioLabs support for planning MOQ, documentation, and sourcing fit.', 'Hello {{contact_name}},\n\nI am contacting you from {{brand_name}} regarding peptide sourcing support for qualified B2B buyers.\n\nFor contract manufacturing teams, we understand the need for organized supply coordination, MOQ planning, documentation support, and batch transparency before commercial decisions move forward.\n\nIf useful, we can share practical next steps for RFQs and documentation review.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', '<p style="margin:0 0 16px;">Hello {{contact_name}},</p><p style="margin:0 0 16px;">I am contacting you from {{brand_name}} regarding peptide sourcing support for qualified B2B buyers.</p><p style="margin:0 0 16px;">For contract manufacturing teams, we understand the need for organized supply coordination, MOQ planning, documentation support, and batch transparency before commercial decisions move forward.</p><p style="margin:0;">If useful, we can share practical next steps for RFQs and documentation review.</p>', 'Hello {{contact_name}},\n\nI am contacting you from {{brand_name}} regarding peptide sourcing support for qualified B2B buyers.\n\nFor contract manufacturing teams, we understand the need for organized supply coordination, MOQ planning, documentation support, and batch transparency before commercial decisions move forward.\n\nIf useful, we can share practical next steps for RFQs and documentation review.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', 0, 1, NOW(), NOW()),
(1, 'Initial Outreach - Research Supply Buyers', 'Research supply buyers', 'Professional sourcing support for {{company_name}}', 'A practical introduction for qualified research supply buyers.', 'Hello {{contact_name}},\n\n{{brand_name}} supports qualified B2B research supply buyers with professional sourcing coordination, MOQ flexibility, documentation support, and batch transparency.\n\nOur communication is focused on supply requirements, documentation expectations, and RFQ coordination without exaggerated claims.\n\nIf {{company_name}} is evaluating sourcing options, we would be glad to share availability and next steps.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', '<p style="margin:0 0 16px;">Hello {{contact_name}},</p><p style="margin:0 0 16px;">{{brand_name}} supports qualified B2B research supply buyers with professional sourcing coordination, MOQ flexibility, documentation support, and batch transparency.</p><p style="margin:0 0 16px;">Our communication is focused on supply requirements, documentation expectations, and RFQ coordination without exaggerated claims.</p><p style="margin:0;">If {{company_name}} is evaluating sourcing options, we would be glad to share availability and next steps.</p>', 'Hello {{contact_name}},\n\n{{brand_name}} supports qualified B2B research supply buyers with professional sourcing coordination, MOQ flexibility, documentation support, and batch transparency.\n\nOur communication is focused on supply requirements, documentation expectations, and RFQ coordination without exaggerated claims.\n\nIf {{company_name}} is evaluating sourcing options, we would be glad to share availability and next steps.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', 0, 1, NOW(), NOW()),
(1, 'Follow-Up 1', 'Other', 'Following up from {{brand_name}}', 'A short follow-up on the earlier sourcing introduction.', 'Hello {{contact_name}},\n\nI wanted to follow up on my previous note from {{brand_name}}.\n\nWe support peptide sourcing with MOQ flexibility, documentation support, batch transparency, and supply coordination for qualified B2B buyers.\n\nIf this is relevant for {{company_name}}, I can share documentation expectations or RFQ next steps.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', '<p style="margin:0 0 16px;">Hello {{contact_name}},</p><p style="margin:0 0 16px;">I wanted to follow up on my previous note from {{brand_name}}.</p><p style="margin:0 0 16px;">We support peptide sourcing with MOQ flexibility, documentation support, batch transparency, and supply coordination for qualified B2B buyers.</p><p style="margin:0;">If this is relevant for {{company_name}}, I can share documentation expectations or RFQ next steps.</p>', 'Hello {{contact_name}},\n\nI wanted to follow up on my previous note from {{brand_name}}.\n\nWe support peptide sourcing with MOQ flexibility, documentation support, batch transparency, and supply coordination for qualified B2B buyers.\n\nIf this is relevant for {{company_name}}, I can share documentation expectations or RFQ next steps.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', 1, 1, NOW(), NOW()),
(1, 'Follow-Up 2', 'Other', 'Closing the loop from {{brand_name}}', 'A final respectful follow-up with a clear opt-out path.', 'Hello {{contact_name}},\n\nI am closing the loop on my previous outreach.\n\nIf peptide sourcing support, documentation alignment, MOQ flexibility, or batch transparency becomes relevant for {{company_name}}, {{brand_name}} would be glad to help coordinate the conversation.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', '<p style="margin:0 0 16px;">Hello {{contact_name}},</p><p style="margin:0 0 16px;">I am closing the loop on my previous outreach.</p><p style="margin:0;">If peptide sourcing support, documentation alignment, MOQ flexibility, or batch transparency becomes relevant for {{company_name}}, {{brand_name}} would be glad to help coordinate the conversation.</p>', 'Hello {{contact_name}},\n\nI am closing the loop on my previous outreach.\n\nIf peptide sourcing support, documentation alignment, MOQ flexibility, or batch transparency becomes relevant for {{company_name}}, {{brand_name}} would be glad to help coordinate the conversation.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', 2, 1, NOW(), NOW()),
(1, 'RFQ Confirmation', 'Other', 'We received your {{brand_name}} RFQ', 'Your RFQ is in and Atlas BioLabs will review the sourcing details.', 'Hello {{contact_name}},\n\nThank you for contacting {{brand_name}}. We received your RFQ details and will review the request for sourcing fit, documentation expectations, MOQ support, and supply coordination next steps.\n\nOur team will follow up using the contact details provided.\n\n{{default_signature}}', '<p style="margin:0 0 16px;">Hello {{contact_name}},</p><p style="margin:0 0 16px;">Thank you for contacting {{brand_name}}. We received your RFQ details and will review the request for sourcing fit, documentation expectations, MOQ support, and supply coordination next steps.</p><p style="margin:0;">Our team will follow up using the contact details provided.</p>', 'Hello {{contact_name}},\n\nThank you for contacting {{brand_name}}. We received your RFQ details and will review the request for sourcing fit, documentation expectations, MOQ support, and supply coordination next steps.\n\nOur team will follow up using the contact details provided.\n\n{{default_signature}}', 9, 1, NOW(), NOW()),
(1, 'Quote Follow-Up', 'Other', 'Following up on your {{brand_name}} quote', 'A practical follow-up after a quote or sourcing discussion.', 'Hello {{contact_name}},\n\nI wanted to follow up on the quote or sourcing discussion with {{brand_name}}.\n\nIf you have questions about MOQ planning, documentation, batch transparency, or next steps, we would be glad to help.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', '<p style="margin:0 0 16px;">Hello {{contact_name}},</p><p style="margin:0 0 16px;">I wanted to follow up on the quote or sourcing discussion with {{brand_name}}.</p><p style="margin:0;">If you have questions about MOQ planning, documentation, batch transparency, or next steps, we would be glad to help.</p>', 'Hello {{contact_name}},\n\nI wanted to follow up on the quote or sourcing discussion with {{brand_name}}.\n\nIf you have questions about MOQ planning, documentation, batch transparency, or next steps, we would be glad to help.\n\n{{default_signature}}\n\nUnsubscribe: {{unsubscribe_link}}', 3, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
subject = VALUES(subject),
preheader = VALUES(preheader),
body = VALUES(body),
body_html = VALUES(body_html),
body_text = VALUES(body_text),
followup_stage = VALUES(followup_stage),
active = VALUES(active),
updated_at = NOW();
