ALTER TABLE rfqs ADD COLUMN IF NOT EXISTS timeline VARCHAR(190) NULL AFTER estimated_quantity;
ALTER TABLE rfqs ADD COLUMN IF NOT EXISTS items_json MEDIUMTEXT NULL AFTER message;
ALTER TABLE rfqs ADD COLUMN IF NOT EXISTS page_url VARCHAR(500) NULL AFTER items_json;
ALTER TABLE rfqs ADD COLUMN IF NOT EXISTS user_agent VARCHAR(500) NULL AFTER page_url;
